import AppKit
import Foundation

/// NSPasteboard has no change notification, so the general pasteboard is polled
/// and `changeCount` is used to detect a new copy.
public final class PasteboardWatcher {
    public var onCopy: ((String) -> Void)?

    /// Markers used by password managers and clipboard tools to opt out of
    /// clipboard history. Respecting them keeps secrets off the network.
    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard: NSPasteboard
    private let interval: TimeInterval
    private var lastChangeCount: Int
    private var suppressed: [(hash: String, at: Date)] = []
    private var lastHandledFingerprint: String?
    private var timer: DispatchSourceTimer?

    public init(pasteboard: NSPasteboard = .general, interval: TimeInterval = 0.5) {
        self.pasteboard = pasteboard
        self.interval = interval
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard timer == nil else { return }
        let timer = DispatchSource.makeTimerSource(queue: .main)
        timer.schedule(deadline: .now() + interval, repeating: interval)
        timer.setEventHandler { [weak self] in self?.poll() }
        timer.resume()
        self.timer = timer
        Log.info("Watching the pasteboard every \(interval)s")
    }

    public func stop() {
        timer?.cancel()
        timer = nil
    }

    /// Puts text received from the phone on the pasteboard without sending it
    /// straight back to the phone.
    public func apply(remoteText text: String) {
        suppress(text: text)
        lastHandledFingerprint = CryptoBox.fingerprint(of: text)
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        Log.info("Applied \(text.utf8.count) bytes from the phone to the pasteboard")
    }

    /// Remembers a value that must not be echoed back, for a short while.
    public func suppress(text: String) {
        let now = Date()
        suppressed.removeAll { now.timeIntervalSince($0.at) > 10 }
        suppressed.append((CryptoBox.fingerprint(of: text), now))
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let types = pasteboard.types ?? []
        if let excluded = Self.excludedTypes.first(where: { types.contains($0) }) {
            Log.debug("Skipping a copy marked as \(excluded.rawValue)")
            return
        }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        guard text.utf8.count <= Wire.maxClipboardBytes else {
            Log.info("Skipping a \(text.utf8.count) byte clipboard, above the \(Wire.maxClipboardBytes) byte limit")
            return
        }

        let fingerprint = CryptoBox.fingerprint(of: text)
        let now = Date()
        suppressed.removeAll { now.timeIntervalSince($0.at) > 10 }
        if suppressed.contains(where: { $0.hash == fingerprint }) {
            Log.debug("Skipping the value we just received from the phone")
            return
        }
        // Another app (or the Android emulator, which mirrors the guest clipboard
        // back to the host) may rewrite the pasteboard with the value we just
        // handled. Forwarding it again would ping pong forever.
        if fingerprint == lastHandledFingerprint {
            Log.debug("Skipping a repeat of the value already in sync")
            return
        }

        lastHandledFingerprint = fingerprint
        Log.info("Local copy detected, \(text.utf8.count) bytes")
        onCopy?(text)
    }
}
